### PR TITLE
Add GitHub action for markdownlint

### PR DESCRIPTION
**Pull request by nielsvanvelzen**

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
I'm not sure why but running markdownlint doesn't do anything in CI. Using the exact same command on my local machine works though.. 🤔

**Comment by thornbill** [comment]
@nielsvanvelzen is there a lint error that it should be catching?

**Comment by nielsvanvelzen** [comment]
This branch is based on the master branch when it failed with 3 issues.

**Review by h1dden-da3m0n — APPROVED** [review]

**Comment by nielsvanvelzen** [comment]
It _should_ work now, if not I'll make another PR later with fixes.

**Review by Maxr1998 — APPROVED** [review]

**Review by h1dden-da3m0n — APPROVED** [review]

**Review by thornbill — APPROVED** [review]

**Pull request merged**
