### PR TITLE
Improved Docker installation Documentation

### PR DESCRIPTION
**Pull request by ThijsvL**
Improved the Docker Documentation to be a little more "Noob" friendly, and added a way to get started with docker by adding the installation steps.

### CODE REVIEW

**Comment by Artiume** [comment]
Any reason to remove the lsio link?

**Comment by ThijsvL** [comment]
> Any reason to remove the lsio link?

Yes, as the Official Docker Header did not have a link but a button, for consistancy I thought it would be nice to have the Ls.io header not be a link but only the button to have a link.

**Comment by ThijsvL** [comment]
> Any reason that you install the docker-compose from the git release instead of apt, i know its a bit older than latest but just as good and is more noob friendly.

I'll have to agree with you, apt-get is easier, my thought was that it was friendlier for people using different systems then Ubuntu + newer release, but you can't go wrong with apt-get

**Comment by nekocentral** [comment]
If i provide the commands and a basic explantion for the docker nvdia part we can mabye also make a noob friendly addition (just did it my self) as i can see your better at writing than me

**Comment by nekocentral** [comment]
# Add the package repositories
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

#Install Nvidia
sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit nvidia-docker2
sudo systemctl restart docker

#Docker compose
runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

also make the docker-compose.yml atleast version 2.3

**Comment by Artiume** [comment]
What about the idea of dropping the the compose version to 2 so that group_add can be added. It's needed to do hwa with our image.

**Comment by nekocentral** [comment]
Just did some testing

nvidia-docker2 is not needed anymore and so does it seem for "runtime: nvidia"

**Comment by nekocentral** [comment]
> What about the idea of dropping the the compose version to 2 so that group_add can be added. It's needed to do hwa with our image.
> 
> Edit :
> Didn't see your comment in time. X)
> Adding this #273
I would personally use 2.3 so you can use the same docker file with nvenc encoding



> #Add the package repositories
> distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
> curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
> curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
> 
> #Install Nvidia
> sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit nvidia-docker2
> sudo systemctl restart docker
> 
> #Docker compose
> runtime: nvidia
> environment:
> - NVIDIA_VISIBLE_DEVICES=all
> 
> also make the docker-compose.yml atleast version 2.3

I used this docker-compose.yml for the docker-nvidia part
```
---
version: "2.3"
services:
  jellyfin-test:
    image: jellyfin/jellyfin
    container_name: jellyfin-test
    user: 1000:1000
    runtime: nvidia
    environment:
      - TZ=$TZ
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /config/test/config:/config
      - /mnt/tv:/media
      - /tmp:/transcode
    ports:
      - 8096:8096
```

**Comment by ThijsvL** [comment]
On it!

**Comment by Artiume** [comment]
I like the updates. I'm ready to merge it. I think the next step should be to break apart all of the install docs to an index and separate pages for each system. Sort of like I did for the network section.

**Pull request merged**
