### PR TITLE
Multipass integration

### PR DESCRIPTION
**Pull request by ethicnology**
https://github.com/canonical/multipass-blueprints/pull/18

### CODE REVIEW

**Comment by ethicnology** [comment]
Can someone help me to fix the build checks, I haven't found any contributor's documentation.

**Comment by nielsvanvelzen** [comment]
Documentation builds are currently broken, the only check you should care about is the markdown linting (which is fine 👍)

**Comment by ethicnology** [comment]
@nielsvanvelzen Any idea why this is pending ?

**Comment by nielsvanvelzen** [comment]
It needs to be reviewed and approved before merging.

**Comment by ethicnology** [comment]
@nielsvanvelzen Do you have any idea of why it takes so long ?

**Comment by nielsvanvelzen** [comment]
We have a new website and this repository is not used anymore. The new site is at https://github.com/jellyfin/jellyfin.org

**Comment by Xyz00777** [comment]
But here are many open issues and merge requests.... Are they migrated to the new?
@nielsvanvelzen

**Comment by nielsvanvelzen** [comment]
Most issues became irrelevant with the new site and pull requests will need to be recreated by their authors.

**Comment by ethicnology** [comment]
@nielsvanvelzen https://github.com/jellyfin/jellyfin.org/pull/302

**Pull request closed without merging**
