### PR TITLE
add [file] directive to traefik config

### PR DESCRIPTION
**Pull request by PrplHaz4**
won't work without it

### CODE REVIEW

**Comment by Artiume** [comment]
Did you test it? I have an external file so I never thought about the fact that might be needed

**Comment by PrplHaz4** [comment]
> 
> 
> Did you test it? I have an external file so I never thought about the fact that might be needed

yup, that's what's running on my test server - the `[file]` directive is there - probably got clipped when I tried to trim things moving it into the docs...

Official Traefik doc on using `[file]`: https://docs.traefik.io/v1.7/configuration/backends/file/

**Comment by huuub** [comment]
Could anybody describe what is the purpose and how do I translate it to traefik2?

**Comment by Artiume** [comment]
This is all for v1.7, there are currently no docs for v2 and they should be written from scratch

**Pull request merged**
