### PR TITLE
Fix line breaks and remove trailing spaces

### PR DESCRIPTION
**Pull request by wwwutz**
- replace double space line breaks with `<br/>` tag
- remove trailing spaces
- replace double-backticks when no single backtick is quoted
- convert ^M endings to LF

### CODE REVIEW

**Comment by dkanada** [comment]
I just merged one pull request with some huge changes to the reverse proxy section, can you rebase against master again? There might be a few more newline changes to make, apologies.

**Comment by wwwutz** [comment]
hrrhrr. nice try to introduce new trailing white spaces 8-)

**Comment by dkanada** [comment]
Blame @Artiume haha, whitespace is hard to catch on GitHub reviews.

**Comment by Artiume** [comment]
They keep me company 😉

**Comment by dkanada** [comment]
If you see any other formatting errors feel free to resolve them. Most of my pull requests here are wording fixes and small tweaks to make the docs look nicer.

**Pull request merged**
